"""add student_id FK to absence and replacement tb

Revision ID: 400d58051af4
Revises: 5d09dda01227
Create Date: 2026-09-30 18:58:52.565217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '400d58051af4'
down_revision: Union[str, Sequence[str], None] = '5d09dda01227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence', sa.Column('student_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'absence', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('replacement', sa.Column('student_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'replacement', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('student', 'day_of_week',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student', 'day_of_week',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'replacement', type_='foreignkey')
    op.drop_column('replacement', 'student_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'absence', type_='foreignkey')
    op.drop_column('absence', 'student_id')
    # ### end Alembic commands ###