"""add is_waived in replacement term

Revision ID: 55f8dde561b3
Revises: 8f4c2d7a1b90
Create Date: 2026-09-28 00:47:44.966998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55f8dde561b3'
down_revision: Union[str, Sequence[str], None] = '8f4c2d7a1b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replacement', sa.Column('is_waived', sa.Boolean(), nullable=False))
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('student', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_table_comment(
        'student',
        existing_comment='list of student names and start/end lesson time',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'student',
        'list of student names and start/end lesson time',
        existing_comment=None,
        schema=None
    )
    op.alter_column('student', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('student', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('replacement', 'is_waived')
    # ### end Alembic commands ###